### ISSUE TITLE
Does not work with the latest pandas 

### ISSUE THREAD

**Issue by matthew-z** [NTMC-Community/MatchZoo#786] opened 2019-09-06 08:41 UTC
### Describe the bug
cannot `import matchzoo` with the latest `pandas` (in my case 0.25.1) due to the recent api changes in `pandas`.

Error message:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/.anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py in pandas(tclass, *targs, **tkwargs)
    593             # pandas>=0.23.0
--> 594             from pandas.core.groupby.groupby import DataFrameGroupBy, \
    595                 SeriesGroupBy, GroupBy, PanelGroupBy

ImportError: cannot import name 'DataFrameGroupBy'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-5-0e79b8132aad> in <module>()
----> 1 import matchzoo

~/.anaconda3/lib/python3.6/site-packages/matchzoo/__init__.py in <module>()
     11 from .version import __version__
     12 
---> 13 from .data_pack import DataPack
     14 from .data_pack import pack
     15 from .data_pack import load_data_pack

~/.anaconda3/lib/python3.6/site-packages/matchzoo/data_pack/__init__.py in <module>()
----> 1 from .data_pack import DataPack, load_data_pack
      2 from .pack import pack

~/.anaconda3/lib/python3.6/site-packages/matchzoo/data_pack/data_pack.py in <module>()
     13 import matchzoo
     14 
---> 15 tqdm.pandas()
     16 
     17 

~/.anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py in pandas(tclass, *targs, **tkwargs)
    595                 SeriesGroupBy, GroupBy, PanelGroupBy
    596         except ImportError:
--> 597             from pandas.core.groupby import DataFrameGroupBy, \
    598                 SeriesGroupBy, GroupBy, PanelGroupBy
    599 

ImportError: cannot import name 'PanelGroupBy'
```
### To Reproduce
`pip install -U pandas`
`import matchzoo`

### Describe your attempts

downgrading pandas to 0.24 can solve this problem
### Context
 - **OS** [MacOS and Ubuntu 18.04]: 
 - **Hardware** [GTX 2080 Ti]:

**Comment by bwanglzu** [comment] 2019-09-06 09:54
@matthew-z can you downgrade your tqdm to `tqdm==4.33.0`?

**Comment by matthew-z** [comment] 2019-09-06 10:15
Right, upgrading tqdm  can solve this problem.

**Comment by bwanglzu** [comment] 2019-09-06 11:00
@matthew-z this is a dependency issue caused by tqdm & pandas, I'll close the issue. Feel free to open new issue for new questions.

**Closed by bwanglzu** 2019-09-06 11:00 UTC
Labels: bug
