### ISSUE TITLE
The computation on NDCG may be wrong

### ISSUE THREAD

**Issue by StKlaas** [NTMC-Community/MatchZoo#598] opened 2019-01-26 09:08 UTC
The original definition of NDCG is to take all the relevant documents in the **corpus** but not in your **prediction** into account when computing IDCG. However, in your implementation, NDCG is computed base on the predicted score and their ground truth. e.g., for a predicted score list y_pred = [0.4, 0.2, 0.5, 0.7] and the corresponding ground-truth y_true = [0, 1, 2, 0], you would treat the golden list as [2, 1, 0, 0]. But, there may be some other relevant documents in the corpus that you do not retrieve, say document a with relevance judgment 2 and document b with relevance judgment 1, then the golden list should be [2, 2, 1, 1] when computing IDCG. The way you compute NDCG would make it much higher than it is in some cases.

Thanks for your attention.

Reference:
https://github.com/NTMC-Community/MatchZoo/blob/master/matchzoo/metrics/normalized_discounted_cumulative_gain.py#L34
https://en.wikipedia.org/wiki/Discounted_cumulative_gain

**Comment by uduse** [comment] 2019-01-26 12:59
Thanks for reporting this. Definitely worth attention.

**Comment by bwanglzu** [comment] 2019-01-29 14:09
@StKlaas Can you review #599 ?

**Comment by faneshion** [comment] 2019-01-30 08:20
@StKlaas you are right for the re-ranking when the candidate list is produced by another algorithm. We will fix this. Thanks for your warning!

**Comment by StKlaas** [comment] 2019-01-30 09:00
@bwanglzu The revised code for dcg is so confusing.
@faneshion yep, when your algorithm cannot recall all the relevant items, that would inevitably hurt the model evaluation, especially in IR. Thanks for your attention again.

**Comment by uduse** [comment] 2019-07-12 02:37
I hope things are working well for you now. I’ll go ahead and close this issue, but I’m happy to continue further discussion whenever needed.

**Closed by uduse** 2019-07-12 02:37 UTC
Labels: 2.0, bug

**Comment by matthew-z** [comment] 2019-09-29 11:33
I am also working on using matchzoo for ad-hoc web search research. The problem is that we usually evaluate models by re-ranking a list of documents retrieved by a simple model such as BM25. For example, we have 2 queries in the test datapack. For query A, we have 1000 docs retrieved from a corpus, and for query B, we have another 1000 docs retrieved from a corpus.  If I understand correctly, matchzoo mixs all the 2000 documents and rank them, so it is different from IR evaluation

My workaround is to create a datapack for each test query, and then take the average.
